name: Integration

on:
  push:
  pull_request:

jobs:

  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version:  '^1.18.0'
      - name: install tools
        run: sudo apt install -y make build-essential gcc redis-tools

      - name: build
        run: make
      - name: test
        run: make test

      - name: test module load
        run: |
          docker build -t redicrypt:testing .
          docker run -d -p 6379:6379 redicrypt:testing
          redis-cli module list|grep redicrypt